name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install C++ dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            antlr4 \
            libantlr4-runtime-dev \
            default-jdk

      - name: Build project
        run: |
            cd ./compiler

            echo $'ANTLRLIB=/usr/lib/x86_64-linux-gnu/libantlr4-runtime.a' >> config.mk
            echo $'ANTLRJAR=/usr/share/java/stringtemplate4.jar:/usr/share/java/antlr4.jar:/usr/share/java/antlr4-runtime.jar:/usr/share/java/antlr3-runtime.jar/:/usr/share/java/treelayout.jar' >> config.mk
            echo $'ANTLRINC=/usr/include/antlr4-runtime' >> config.mk
            echo $'ANTLR=java -cp $(ANTLRJAR) org.antlr.v4.Tool' >> config.mk

            make
    
      - name: Archive ifcc
        uses: actions/upload-artifact@v4
        with:
          name: ifcc
          path: ./compiler/ifcc

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Download ifcc
        uses: actions/download-artifact@v4
        with:
          name: ifcc
          path: ./compiler/

      - name: Run tests
        run: |
          chmod +x ./compiler/ifcc
          python -m pytest tests/ --junit-xml=test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./ifcc-test-output

      - name: Surface failing tests
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true
          title: Test results